package com.cox.bmw.iplookup.dao.model;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.cox.bmw.iplookup.model.DataService;

@DynamoDBTable(tableName = "CustomerAccountInfo")
public class CustomerAccountInfo {
	
	private String id;
	private String ipaddress;
	private String accountNumber9;
	private String accountStatus;
	private String accountType;
	private String siteId;
	private List<DataService> dataService;
	private String leaseStartDate;
	private String leaseEndDate;
	
    
	public CustomerAccountInfo()
	{
		
	}
	
	public CustomerAccountInfo(String ipaddress, String accountNumber9, String accountStatus, String accountType, String siteId, List<DataService> dataService, String leaseStartDate, String leaseEndDate ) {
        this.ipaddress = ipaddress;
        this.accountNumber9 = accountNumber9;
        this.accountStatus = accountStatus;
        this.accountType = accountType;
        this.siteId = siteId;
        this.dataService = dataService;
        this.leaseStartDate = leaseStartDate;
        this.leaseEndDate = leaseEndDate;
    }
	
	/**
	 * @return the id
	 */
	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	/**
	 * @return the ipaddress
	 */
	@DynamoDBAttribute
	public String getIpaddress() {
		return ipaddress;
	}
	/**
	 * @return the accountNumber9
	 */
	@DynamoDBAttribute
	public String getAccountNumber9() {
		return accountNumber9;
	}
	/**
	 * @return the accountStatus
	 */
	@DynamoDBAttribute
	public String getAccountStatus() {
		return accountStatus;
	}
	/**
	 * @return the accountType
	 */
	@DynamoDBAttribute
	public String getAccountType() {
		return accountType;
	}
	/**
	 * @return the siteId
	 */
	@DynamoDBAttribute
	public String getSiteId() {
		return siteId;
	}
	/**
	 * @return the dataService
	 */
	@DynamoDBAttribute
	public List<DataService> getDataService() {
		return dataService;
	}
	/**
	 * @return the leaseStartDate
	 */
	@DynamoDBAttribute
	public String getLeaseStartDate() {
		return leaseStartDate;
	}
	/**
	 * @return the leaseEndDate
	 */
	@DynamoDBAttribute
	public String getLeaseEndDate() {
		return leaseEndDate;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}
	/**
	 * @param ipaddress the ipaddress to set
	 */
	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}
	/**
	 * @param accountNumber9 the accountNumber9 to set
	 */
	public void setAccountNumber9(String accountNumber9) {
		this.accountNumber9 = accountNumber9;
	}
	/**
	 * @param accountStatus the accountStatus to set
	 */
	public void setAccountStatus(String accountStatus) {
		this.accountStatus = accountStatus;
	}
	/**
	 * @param accountType the accountType to set
	 */
	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}
	/**
	 * @param siteId the siteId to set
	 */
	public void setSiteId(String siteId) {
		this.siteId = siteId;
	}
	/**
	 * @param dataService the dataService to set
	 */
	public void setDataService(List<DataService> dataService) {
		this.dataService = dataService;
	}
	/**
	 * @param leaseStartDate the leaseStartDate to set
	 */
	public void setLeaseStartDate(String leaseStartDate) {
		this.leaseStartDate = leaseStartDate;
	}
	/**
	 * @param leaseEndDate the leaseEndDate to set
	 */
	public void setLeaseEndDate(String leaseEndDate) {
		this.leaseEndDate = leaseEndDate;
	}
	
	


}
